import React, { useState, useEffect } from 'react';
import { 
  FileText, Upload, Plus, CheckCircle2, Clock, 
  AlertTriangle, Hospital, ArrowRight, Search, Filter, ShieldCheck
} from 'lucide-react';
import { getMyReports } from '../../services/medicalReportsService';
import ReportDetailModal from '../../components/ReportDetailModal';
import { useNavigate } from 'react-router-dom';

const MyReports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('ALL'); // ALL, HOSPITAL, UPLOADED
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedReport, setSelectedReport] = useState(null);
  const [isDetailOpen, setIsDetailOpen] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const data = await getMyReports();
      setReports(data || []);
    } catch (err) {
      console.error("Failed to load medical records:", err);
    } finally {
      setLoading(false);
    }
  };

  const filteredReports = reports.filter(r => {
    const matchesTab = 
      activeTab === 'ALL' ||
      (activeTab === 'HOSPITAL' && r.report_source === 'hospital') ||
      (activeTab === 'UPLOADED' && r.report_source === 'existing_upload');

    const matchesSearch = 
      r.report_title?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      r.department_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      r.doctor_name?.toLowerCase().includes(searchTerm.toLowerCase());

    return matchesTab && matchesSearch;
  });

  const openReport = (rep) => {
    setSelectedReport(rep);
    setIsDetailOpen(true);
  };

  return (
    <div className="min-h-screen bg-[#F6F9FB] p-6 lg:p-8">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* Page Header */}
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-bold uppercase tracking-wider text-[#0F9D8A] bg-teal-50 px-2.5 py-0.5 rounded">
                Electronic Health Records
              </span>
              <span className="text-xs text-slate-400 font-medium">• Diagnostic Vault</span>
            </div>
            <h1 className="text-xl font-bold text-slate-900 mt-1">My Medical Reports & Laboratory Records</h1>
            <p className="text-xs text-slate-500 mt-0.5">
              Access hospital-issued diagnostic charts and external laboratory uploads with AI pre-analysis.
            </p>
          </div>

          <button
            onClick={() => navigate('/own-report')}
            className="px-4 py-2 bg-[#0F9D8A] hover:bg-teal-700 text-white text-xs font-semibold rounded-lg transition-colors inline-flex items-center gap-1.5 self-start sm:self-center"
          >
            <Upload size={14} />
            <span>Upload New Report</span>
          </button>
        </div>

        {/* 2 Primary Action Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {/* Hospital Internal Records */}
          <div className="bg-white rounded-xl p-5 border border-slate-200 shadow-xs flex flex-col justify-between space-y-4">
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <span className="text-[10px] font-bold uppercase tracking-wider text-[#0F9D8A] bg-teal-50 px-2 py-0.5 rounded">
                  Hospital EMR
                </span>
              </div>
              <h2 className="text-base font-bold text-slate-900">Hospital Medical Records</h2>
              <p className="text-xs text-slate-500 leading-relaxed">
                Official diagnostic tests, pathology analyses, and consultation summaries generated by Health Analyzer Hospital clinicians.
              </p>
            </div>
            <button
              onClick={() => setActiveTab('HOSPITAL')}
              className="py-2 px-3 bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold rounded-lg transition-colors text-center"
            >
              Filter Hospital Records
            </button>
          </div>

          {/* External Report OCR Processing */}
          <div className="bg-white rounded-xl p-5 border border-slate-200 shadow-xs flex flex-col justify-between space-y-4">
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <span className="text-[10px] font-bold uppercase tracking-wider text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded">
                  External OCR Pipeline
                </span>
              </div>
              <h2 className="text-base font-bold text-slate-900">External Report Ingestion</h2>
              <p className="text-xs text-slate-500 leading-relaxed">
                Have a report from an outside diagnostic center? Upload a PDF or scan to automatically extract parameters and trigger AI pre-analysis.
              </p>
            </div>
            <button
              onClick={() => navigate('/own-report')}
              className="py-2 px-3 bg-[#0F9D8A] hover:bg-teal-700 text-white text-xs font-semibold rounded-lg transition-colors text-center inline-flex items-center justify-center gap-1.5"
            >
              <span>Upload or Enter Values</span>
              <ArrowRight size={13} />
            </button>
          </div>
        </div>

        {/* Filter & Listing Card */}
        <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 pb-3">
            <div className="flex items-center gap-2">
              {['ALL', 'HOSPITAL', 'UPLOADED'].map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors ${
                    activeTab === tab
                      ? 'bg-slate-900 text-white'
                      : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                  }`}
                >
                  {tab === 'ALL' ? `All Records (${reports.length})` : tab === 'HOSPITAL' ? 'Hospital Issued' : 'External Uploads'}
                </button>
              ))}
            </div>

            <div className="relative w-full sm:w-64">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
              <input
                type="text"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                placeholder="Search records by title or department..."
                className="w-full pl-8 pr-3 py-1.5 bg-slate-50 border border-slate-200 rounded-lg text-xs focus:outline-none focus:border-[#0F9D8A]"
              />
            </div>
          </div>

          {/* Records Table or Empty State */}
          {loading ? (
            <p className="text-xs text-slate-400 py-10 text-center font-medium">Loading clinical documents...</p>
          ) : filteredReports.length === 0 ? (
            <div className="py-12 text-center space-y-3">
              <div className="w-12 h-12 rounded-xl bg-slate-50 text-slate-400 flex items-center justify-center mx-auto border border-slate-200">
                <FileText size={22} />
              </div>
              <h3 className="text-sm font-bold text-slate-800">No medical reports found</h3>
              <p className="text-xs text-slate-500 max-w-sm mx-auto">
                No clinical records match this filter. Upload a laboratory panel to view automated parameter extraction.
              </p>
              <button
                onClick={() => navigate('/own-report')}
                className="px-4 py-2 bg-[#0F9D8A] hover:bg-teal-700 text-white text-xs font-semibold rounded-lg transition-colors inline-flex items-center gap-1.5"
              >
                <Upload size={14} />
                <span>Upload Report</span>
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {filteredReports.map((report) => (
                <div
                  key={report.id}
                  onClick={() => openReport(report)}
                  className="bg-white p-4 rounded-xl border border-slate-200 hover:border-slate-300 transition-all cursor-pointer shadow-xs space-y-3 flex flex-col justify-between"
                >
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className={`text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded ${
                        report.report_source === 'hospital' 
                          ? 'bg-teal-50 text-teal-700 border border-teal-200' 
                          : 'bg-slate-100 text-slate-700'
                      }`}>
                        {report.report_source === 'hospital' ? 'Hospital Record' : 'External Processed'}
                      </span>
                      <span className="text-[11px] text-slate-400 font-medium">{report.report_date}</span>
                    </div>

                    <h3 className="text-sm font-bold text-slate-900 line-clamp-1">{report.report_title}</h3>
                    <p className="text-xs text-slate-500">{report.department_name || 'General Medicine'}</p>
                  </div>

                  <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-xs">
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-slate-100 text-slate-600 uppercase">
                      {report.status}
                    </span>
                    <span className="text-xs font-semibold text-[#0F9D8A] hover:underline flex items-center gap-1">
                      View Details →
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Clinical Report Detail Modal */}
      <ReportDetailModal
        report={selectedReport}
        isOpen={isDetailOpen}
        onClose={() => setIsDetailOpen(false)}
      />
    </div>
  );
};

export default MyReports;
